Leocroce/bookshelf_v1

- src/app/modelosInterface/sagas.ts
- src/assets/sagas.json
Adicionando:
[ x ] Endpoint sagas  
[ x ] Interface  sagas.
> Acionando endpoint e interface de sagas

- src/app/servicosInterface/sagas.service.spec.ts
- src/app/servicosInterface/sagas.service.ts
> Serviço saga

- src/app/app-not-found/app-not-found.component.html
- src/app/app-not-found/app-not-found.component.scss
- src/app/app-not-found/app-not-found.component.spec.ts
- src/app/app-not-found/app-not-found.component.ts
- src/app/app-routing.module.ts
- src/app/app.module.ts
> implementacao rotas desconhecida

- src/app/app-not-found/app-not-found.component.html
- src/app/app-not-found/app-not-found.component.scss
- src/app/app-not-found/app-not-found.component.spec.ts
- src/app/app-not-found/app-not-found.component.ts
- src/app/app-routing.module.ts
- src/app/app.module.ts
> atualização rota desconhecida

- src/app/app-login/app-login.component.ts
> Correção bug falha de login

- src/app/navegacao/navegacao.component.html
> Link na logo

- src/app/app-login/app-login.component.html
- src/app/app-login/app-login.component.ts
- src/app/app.module.ts
> Verificacao de login de robos

- src/app/app-login/app-login.component.ts
> Rotina para limpar campos após o login

- src/app/cdd/classes/classes.component.html
- src/assets/generos.json
> Correção de erros de português do módulo CDD

- src/app/app-login/app-login.component.html
- src/app/app-login/app-login.component.scss
- src/app/app-login/app-login.component.ts
> Melhorias Dialogo de Login

- src/app/sagas/sagas.component.html
> Correção no link e atualização de titulo

- src/app/navegacao/navegacao.component.ts
> Falha de Logout

- src/app/app-cadastro/app-cadastro.component.html
- src/app/app-cadastro/app-cadastro.component.scss
- src/app/app-cadastro/app-cadastro.component.ts
- src/app/app.module.ts
> Melhorias para Tela de Cadastro

- src/app/modelosInterface/artes.ts
- src/assets/artes.json
> Endpoint Artes

- src/app/servicosInterface/artes.service.spec.ts
- src/app/servicosInterface/artes.service.ts
> Criação do Serviço de Artes

- src/app/feed/feed.component.html
- src/app/feed/feed.component.scss
> Mensagem de boas vindas do usuário1

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/isbn/isbn.component.html
- src/app/isbn/isbn.component.scss
- src/app/isbn/isbn.component.spec.ts
- src/app/isbn/isbn.component.ts
- src/assets/menuNavegador.json
> Pagina de Instruções sobre ISBN

- src/app/app-login/app-login.component.ts
> Tratar erros do Auth Firebase

- src/app/app-cadastro/app-cadastro.component.html
> Correção nos toasts de cadastro

- src/app/modelosInterface/especialMes.ts
- src/assets/especialMes.json
> Criação do json e interface da página Especial do mês

- src/app/servicosInterface/especial-mes.service.spec.ts
- src/app/servicosInterface/especial-mes.service.ts
> Criação do serviço para ser injetado no componente do Especial do Mês

- src/app/app-cadastro/app-cadastro.component.ts
> Tratar os erros de cadastro

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/especial-mes/especial-mes.component.html
- src/app/especial-mes/especial-mes.component.scss
- src/app/especial-mes/especial-mes.component.spec.ts
- src/app/especial-mes/especial-mes.component.ts
- src/assets/especialMes.json
- src/assets/menuNavegador.json
> Criação da Página Especial do Mês

- src/app/feed/feed.component.html
- src/app/feed/feed.component.scss
- src/app/feed/feed.component.ts
- src/app/servicosInterface/dashboard.service.ts
> Implementação de spinner para carregamento da página

- src/app/feed/feed.component.html
- src/app/feed/feed.component.scss
- src/assets/dashboard.json
> Melhorias na disposição dos cards

- src/app/modelosInterface/empreendedorismo.ts
- src/assets/empreendedorismo.json
> Criação Endpoint de Empreendedorismo

- src/app/app-login/app-login.component.html
- src/app/app-login/app-login.component.ts
> Refatorando Recaptcha

- src/app/servicosInterface/empreendedorismo.service.spec.ts
- src/app/servicosInterface/empreendedorismo.service.ts
> Serviço de Empreendedorismo

- src/app/modelosInterface/teatro.ts
- src/assets/teatro.json
> Endpoint Teatro

- src/app/servicosInterface/psicologia.service.spec.ts
- src/app/servicosInterface/psicologia.service.ts
> Criação serviço de psicologia

- src/app/modelosInterface/tecnologia.ts
- src/assets/tecnologia.json
> Endpoint de tecnologia

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/empreendedorismo/empreendedorismo.component.html
- src/app/empreendedorismo/empreendedorismo.component.scss
- src/app/empreendedorismo/empreendedorismo.component.spec.ts
- src/app/empreendedorismo/empreendedorismo.component.ts
- src/app/modelosInterface/empreendedorismo.ts
- src/app/servicosInterface/empreendedorismo.service.ts
- src/assets/empreendedorismo.json
- src/assets/menuNavegador.json
> Criação component de Empreendedorismo

- src/app/servicosInterface/teatro.service.spec.ts
- src/app/servicosInterface/teatro.service.ts
> Serviço de Teatro

- src/app/criticas/service/criticas.service.spec.ts
- src/app/criticas/service/criticas.service.ts
> Montagem do serviço modular de Criticas

- src/app/servicosInterface/tecnologia.service.spec.ts
- src/app/servicosInterface/tecnologia.service.ts
> Serviço de Tecnologia

- src/app/app-cadastro/app-cadastro.component.ts
> Rotira para limpar campo após cadastro

- src/app/servicosInterface/direito.service.spec.ts
- src/app/servicosInterface/direito.service.ts
> Criação de serviço para a página de Direito

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/psicologia/psicologia.component.html
- src/app/psicologia/psicologia.component.scss
- src/app/psicologia/psicologia.component.spec.ts
- src/app/psicologia/psicologia.component.ts
- src/app/sagas/sagas.component.html
- src/assets/menuNavegador.json
> Criação página Psicologia

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/artes/artes.component.html
- src/app/artes/artes.component.scss
- src/app/artes/artes.component.spec.ts
- src/app/artes/artes.component.ts
- src/app/modelosInterface/artes.ts
- src/app/servicosInterface/artes.service.ts
- src/assets/artes.json
- src/assets/menuNavegador.json
> Criação do componente de Artes

- src/app/modelosInterface/sugestoes.ts
- src/assets/sugestoes.json
> Criação do Endpoint de Sugestões

- src/app/servicosInterface/sugestoes.service.spec.ts
- src/app/servicosInterface/sugestoes.service.ts
> Criação do serviço de sugestões

- src/app/modelosInterface/biblioteconomia.ts
- src/assets/biblioteconomia.json
> Endpoint de Biblioteconomia

- src/app/servicosInterface/biblioteconomia.service.spec.ts
- src/app/servicosInterface/biblioteconomia.service.ts
> Serviço de Biblioteconomia

- src/app/criticas/criticas/criticas.component.html
- src/app/criticas/dialogos/criticas-dialogo/criticas-dialogo.component.html
- src/app/criticas/dialogos/criticas-dialogo/criticas-dialogo.component.spec.ts
- src/app/criticas/dialogos/criticas-dialogo/criticas-dialogo.component.ts
> Criação do dialogo de criticas

- src/app/app-compartilhado/app-material/app-material.module.ts
- src/app/cdd/cdd.module.ts
- src/app/cdd/classes/classes.component.html
- src/app/cdd/classes/classes.component.scss
- src/app/cdd/classes/classes.component.ts
- src/app/cdd/service/generos.service.ts
> implementação rotina de busca por genero component CDD

- src/app/navegacao/navegacao.component.html
> input email no alto do menu

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/sugestoes/sugestoes.component.html
- src/app/sugestoes/sugestoes.component.scss
- src/app/sugestoes/sugestoes.component.spec.ts
- src/app/sugestoes/sugestoes.component.ts
- src/assets/menuNavegador.json
- src/assets/sugestoes.json
> Criação do componente de Sugestões

- src/app/app-cadastro/app-cadastro.component.html
- src/app/app-cadastro/app-cadastro.component.ts
- src/app/servicosInterface/autenticacao-firebase.service.ts
> Aplicar URL de Foto via Cadastro

- src/app/navegacao/navegacao.component.html
- src/app/navegacao/navegacao.component.scss
> Melhoria no botão do usuário

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/teatro/teatro.component.html
- src/app/teatro/teatro.component.scss
- src/app/teatro/teatro.component.spec.ts
- src/app/teatro/teatro.component.ts
- src/assets/menuNavegador.json
> Página Teatro

- src/app/navegacao/navegacao.component.html
- src/app/navegacao/navegacao.component.scss
- src/app/navegacao/navegacao.component.ts
> troca de cores na toolbar

- src/app/navegacao/navegacao.component.html
> refatorando cores botões

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/tecnologia/tecnologia.component.html
- src/app/tecnologia/tecnologia.component.scss
- src/app/tecnologia/tecnologia.component.spec.ts
- src/app/tecnologia/tecnologia.component.ts
- src/assets/menuNavegador.json
- src/assets/tecnologia.json
> Página de Tecnologia

- src/app/servicosInterface/sugestoes.service.ts
- src/app/sugestoes/sugestoes.component.html
- src/app/sugestoes/sugestoes.component.scss
- src/app/sugestoes/sugestoes.component.ts
> Criação de um formulário reativo que executa a busca nas sugestões através do título do livro de sugestões.

- src/app/perfil/perfil.component.html
- src/app/perfil/perfil.component.scss
> Refatorando a página de perfil

- src/app/app-login/app-login.component.html
- src/app/app-login/app-login.component.ts
- src/app/servicosInterface/autenticacao-firebase.service.ts
> Método de login através do Google Contas

- src/app/sagas/sagas.component.html
- src/app/sagas/sagas.component.scss
- src/app/sagas/sagas.component.ts
- src/app/servicosInterface/sagas.service.ts
> Criação de uma busca de sagas por um campo de título

- src/app/navegacao/navegacao.component.html
- src/app/navegacao/navegacao.component.scss
> melhoriatoolbar

- src/app/app-login/app-login.component.html
- src/app/app-login/app-login.component.scss
- src/app/app-login/app-login.component.ts
- src/app/app-recuperar-senha/app-recuperar-senha.component.html
- src/app/app-recuperar-senha/app-recuperar-senha.component.scss
- src/app/app-recuperar-senha/app-recuperar-senha.component.spec.ts
- src/app/app-recuperar-senha/app-recuperar-senha.component.ts
- src/app/app-routing.module.ts
- src/app/app.module.ts
> Implementação de Tela de Recuperar Senha

- src/app/cdd/classes/classes.component.html
- src/app/cdd/classes/classes.component.scss
> Ajustes Tabela de CDD

- src/app/feed/feed.component.html
- src/app/feed/feed.component.scss
> Melhoria de divisores Feed

- src/app/detalhe-saga/detalhe-saga.component.html
- src/app/detalhe-saga/detalhe-saga.component.scss
- src/app/sagas/sagas.component.html
- src/app/sagas/sagas.component.scss
- src/assets/sagas.json
> Melhorias em sagas

- src/app/feed/feed.component.html
- src/app/feed/feed.component.scss
- src/assets/dashboard.json
> Modelo de visualização Dashboard

- src/app/app-routing.module.ts
> Verificação de rotas e validação de acesso aos recursos da aplicação.

- src/app/app-cadastro/app-cadastro.component.html
- src/app/app-login/app-login.component.html
- src/app/app-recuperar-senha/app-recuperar-senha.component.html
- src/app/app.module.ts
- src/app/criticas/criticas/criticas.component.html
- src/app/feed/feed.component.html
- src/app/navegacao/navegacao.component.html
- src/app/navegacao/navegacao.component.spec.ts
> Implementação tooltips nos buttons mais utilizados

- src/app/app-routing.module.ts
- src/app/biblioteconomia/biblioteconomia-routing.module.ts
- src/app/biblioteconomia/biblioteconomia.module.ts
- src/app/biblioteconomia/classes/biblioteconomia.component.html
- src/app/biblioteconomia/classes/biblioteconomia.component.scss
- src/app/biblioteconomia/classes/biblioteconomia.component.spec.ts
- src/app/biblioteconomia/classes/biblioteconomia.component.ts
- src/app/biblioteconomia/modelos/biblioteconomia.ts
- src/app/biblioteconomia/service/biblioteconomia.service.spec.ts
- src/app/biblioteconomia/service/biblioteconomia.service.ts
- src/app/servicosInterface/biblioteconomia.service.ts
- src/assets/biblioteconomia.json
- src/assets/menuNavegador.json
> Modulo de Biblioteconomia

- src/app/app-routing.module.ts
- src/app/navegacao/navegacao.component.html
> Melhoria no menu lateral
